version: '2'
services:
  web:
    build:
      context: https://github.com/FearlessSolutions/canvas-lms.git#stable
    volumes:
      - canvas-rce_node_modules:/usr/src/app/packages/canvas-rce/node_modules
      - canvas-rce_lib:/usr/src/app/packages/canvas-rce/lib
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PASSENGER_STARTUP_TIMEOUT: 3600
      RAILS_ENV: ${RAILS_ENV}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CANVAS_LMS_ADMIN_EMAIL: ${CANVAS_LMS_ADMIN_EMAIL}
      CANVAS_LMS_ADMIN_PASSWORD: ${CANVAS_LMS_ADMIN_PASSWORD}
      CANVAS_LMS_ACCOUNT_NAME: ${CANVAS_LMS_ACCOUNT_NAME}
      CANVAS_LMS_STATS_COLLECTION: ${CANVAS_LMS_STATS_COLLECTION}
      APP_PORT: ${APP_DOMAIN}
      APP_DOMAIN: ${VIRTUAL_HOST}
    links:
      - jobs
      - webpack
      - postgres
      - redis
  jobs:
    build:
      context: https://github.com/FearlessSolutions/canvas-lms.git#stable
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PASSENGER_STARTUP_TIMEOUT: 3600
      RAILS_ENV: ${RAILS_ENV}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CANVAS_LMS_ADMIN_EMAIL: ${CANVAS_LMS_ADMIN_EMAIL}
      CANVAS_LMS_ADMIN_PASSWORD: ${CANVAS_LMS_ADMIN_PASSWORD}
      CANVAS_LMS_ACCOUNT_NAME: ${CANVAS_LMS_ACCOUNT_NAME}
      CANVAS_LMS_STATS_COLLECTION: ${CANVAS_LMS_STATS_COLLECTION}
      APP_PORT: ${APP_DOMAIN}
      APP_DOMAIN: ${VIRTUAL_HOST}
    command: bundle exec script/delayed_job run
    volumes:
      - canvas-rce_node_modules:/usr/src/app/packages/canvas-rce/node_modules
      - canvas-rce_lib:/usr/src/app/packages/canvas-rce/lib
  webpack:
    build:
      context: https://github.com/FearlessSolutions/canvas-lms.git#stable
    volumes:
      - canvas-rce_node_modules:/usr/src/app/packages/canvas-rce/node_modules
      - canvas-rce_lib:/usr/src/app/packages/canvas-rce/lib
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      PASSENGER_STARTUP_TIMEOUT: 3600
      RAILS_ENV: ${RAILS_ENV}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CANVAS_LMS_ADMIN_EMAIL: ${CANVAS_LMS_ADMIN_EMAIL}
      CANVAS_LMS_ADMIN_PASSWORD: ${CANVAS_LMS_ADMIN_PASSWORD}
      CANVAS_LMS_ACCOUNT_NAME: ${CANVAS_LMS_ACCOUNT_NAME}
      CANVAS_LMS_STATS_COLLECTION: ${CANVAS_LMS_STATS_COLLECTION}
      APP_PORT: ${APP_DOMAIN}
      APP_DOMAIN: ${VIRTUAL_HOST}
    command: yarn run webpack
  postgres:
    build:
      context: https://github.com/FearlessSolutions/canvas-lms.git#stable:docker-compose/postgres
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    links:
      - postgres
  redis:
    image: redis:alpine
  cassandra:
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
  rce-api:
    build:
      context: https://github.com/instructure/canvas-rce-api.git#master
    environment:
      # VIRTUAL_HOST: ${RCE_VIRTUAL_HOST}
      NODE_ENV: ${NODE_ENV}
      STATSD_HOST: ${STATSD_HOST}
      STATSD_PORT: ${STATSD_PORT}
      ECOSYSTEM_SECRET: ${ECOSYSTEM_SECRET}
      ECOSYSTEM_KEY: ${ECOSYSTEM_KEY}
      CIPHER_PASSWORD: ${CIPHER_PASSWORD}
volumes:
  canvas-rce_node_modules: {}
  canvas-rce_lib: {}
