version: 2
executors:
  working_directory: /
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Download Environment File from S3
          command: |
            aws s3 cp s3://${CONFIG_BUCKET}/ . --recursive
          name: Build Docker Images
          command: |
            docker-compose build
          no_output_timeout: 30m
      - run:
          name: Tag and Push Docker Images
          command: |
            login="$(aws ecr get-login)"
            ${login}
            images=$(docker-compose images -q | xargs docker inspect --format='{{ index .RepoTags 0}}' | cut -d':' -f1)
            for image in ${images}
            do
              aws ecr create-repository --repository-name "${PROJECT_NAME}"/"${image}"
              docker tag "${image}" "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"${PROJECT_NAME}"/"${image}":${CIRCLE_SHA1}"
              docker push "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/"${PROJECT_NAME}"/"${image}":${CIRCLE_SHA1}"
            done
          no_output_timeout: 30m
